package dev.gmodcraft.link;

/**
 * Mirror of protocol/gmodcraft_protocol.h: every constant there, by the rule kFooBar -> FOO_BAR.
 * GENERATED by tools/gen_proto_java.py; ProtoLayoutTest parses the header and fails the build on
 * any difference, in either direction. Offsets are relative to the region (or record) named by
 * their prefix; see the header.
 */
public final class Proto {
	private Proto() {
	}

	public static final int MAGIC = 0x52434D47;
	public static final int VERSION = 45;
	public static final double UNITS_PER_BLOCK = 40.0;
	public static final int HEARTBEAT_TIMEOUT_MS = 8000;
	// enum LinkKind
	public static final int LINK_CLIENT = 1;
	public static final int LINK_SERVER = 2;

	// ==== Common header @0x0 of both links ====
	public static final long H_MAGIC = 0x00L;
	public static final long H_VERSION = 0x04L;
	public static final long H_LINK_KIND = 0x08L;
	public static final long H_MAPPING_BYTES = 0x10L;
	public static final long H_SESSION_NONCE = 0x18L;
	public static final long H_HOST_HEARTBEAT_NS = 0x20L;
	public static final long H_MC_HEARTBEAT_NS = 0x28L;
	public static final long H_MC_NONCE = 0x30L;
	public static final long LINK_HEADER_BYTES = 0x40L;

	// ==== Shared structs (used by one or both links) ====

	// water grid (host -> MC, seqlock)
	public static final int WATER_GRID_SIZE = 16;
	public static final float NO_WATER = -1.0e30F;
	public static final long WG_SEQ = 0x00L;
	public static final long WG_ORIGIN_X = 0x04L;
	public static final long WG_ORIGIN_Z = 0x08L;
	public static final long WG_WORLD_ID = 0x0CL;
	public static final long WG_SURFACE = 0x10L;
	public static final long WATER_GRID_BYTES = 0x410L;

	// actor table (host -> MC, seqlock)
	public static final int MAX_ACTORS = 256;
	// enum ActorFlags
	public static final int ACTOR_HOSTILE = 0x1;
	public static final int ACTOR_DEAD = 0x2;
	public static final int ACTOR_ESSENTIAL = 0x4;
	public static final int ACTOR_IN_COMBAT = 0x8;
	public static final long AR_ENT_ID = 0x00L;
	public static final long AR_FLAGS = 0x04L;
	public static final long AR_X = 0x08L;
	public static final long AR_Y = 0x0CL;
	public static final long AR_Z = 0x10L;
	public static final long AR_YAW = 0x14L;
	public static final long AR_WIDTH = 0x18L;
	public static final long AR_HEIGHT = 0x1CL;
	public static final long AR_HEALTH_FRAC = 0x20L;
	public static final long AR_TIER = 0x24L;
	public static final long AR_NAME = 0x28L;
	public static final long ACTOR_NAME_BYTES = 24L;
	public static final long ACTOR_RECORD_BYTES = 64L;
	public static final long AT_SEQ = 0x00L;
	public static final long AT_COUNT = 0x04L;
	public static final long AT_RECORDS = 0x40L;
	public static final long ACTOR_TABLE_BYTES = 0x4040L;

	// collision ring (host -> MC)
	public static final long CR_HEAD = 0x00L;
	public static final long CR_TAIL = 0x40L;
	public static final long CR_DATA = 0x80L;
	// enum ColType
	public static final int COL_PAD = 0;
	public static final int COL_CLEAR = 1;
	public static final int COL_REGION = 2;
	public static final int COL_TRIS = 3;
	public static final int COL_WEAPON_ICON = 4;
	// enum WeaponIconFormat
	public static final int ICON_RGBA8 = 1;
	public static final long WI_HASH = 0x00L;
	public static final long WI_W = 0x04L;
	public static final long WI_H = 0x06L;
	public static final long WI_FORMAT = 0x08L;
	public static final long WEAPON_ICON_HEADER_BYTES = 16L;
	public static final int WEAPON_ICON_MAX_SIDE = 64;
	public static final long WEAPON_ICON_MAX_BYTES = 16400L;
	// enum ColTriFlags
	public static final int TRI_STAIR_HELPER = 0x1;
	public static final int TRI_DIGGABLE = 0x2;
	public static final int TRI_GHOST = 0x4;
	public static final int TRI_TERRAIN = 0x8;
	public static final int TRI_DYNAMIC = 0x10;
	public static final int TRI_MATERIAL_SHIFT = 8;
	public static final int TRI_ENTITY_SHIFT = 16;
	public static final long COL_TRI_BYTES = 40L;
	public static final long COL_MSG_HEADER_BYTES = 8L;
	public static final int COL_REGION_SIZE = 8;
	public static final long COL_REGION_HEADER_BYTES = 32L;
	public static final long COL_BLOCK_BYTES = 80L;
	// enum DigMaterial
	public static final int DIG_NONE = 0;
	public static final int DIG_GRASS = 1;
	public static final int DIG_DIRT = 2;
	public static final int DIG_STONE = 3;
	public static final int DIG_COBBLE = 4;
	public static final int DIG_SNOW = 5;
	public static final int DIG_ICE = 6;
	public static final int DIG_SAND = 7;
	public static final int DIG_GRAVEL = 8;
	public static final int DIG_MUD = 9;
	public static final int DIG_OAK_LOG = 10;
	public static final int DIG_SPRUCE_LOG = 11;
	public static final int DIG_BIRCH_LOG = 12;
	public static final int DIG_PLANKS = 13;
	public static final int DIG_METAL = 14;
	public static final int DIG_GLASS = 15;
	public static final int DIG_ORGANIC = 16;
	public static final int DIG_CLOTH = 17;
	public static final int DIG_BONE = 18;
	public static final int DIG_WEB = 19;
	public static final int DIG_ASH = 20;
	public static final int DIG_BEDROCK = 21;
	public static final int DIG_MATERIAL_COUNT = 22;

	// map slots (D-003, docs/DESIGN.md section 3)
	public static final int SLOT_BLOCKS = 2048;
	public static final int ANCHOR_FLOOR_Y = 64;
	public static final int ANCHOR_WAIT_MS = 30000;

	// link stats (both links, debug only)
	public static final int MAX_STAT_RINGS = 4;
	// enum ClientStatRing
	public static final int CL_RING_INPUT = 0;
	public static final int CL_RING_COLLISION = 1;
	public static final int CL_RING_RENDER = 2;
	public static final int CL_RING_EVENTS = 3;
	// enum ServerStatRing
	public static final int SV_RING_HOST_EVENTS = 0;
	public static final int SV_RING_COLLISION = 1;
	public static final int SV_RING_EVENTS = 2;
	public static final int SV_RING_BLOCKS = 3;
	public static final long RS_MESSAGES = 0x00L;
	public static final long RS_BYTES = 0x08L;
	public static final long RS_DROPS = 0x10L;
	public static final long RS_FILL = 0x18L;
	public static final long RS_HIGH_WATER = 0x20L;
	public static final long RS_BYTES_PER_SEC = 0x28L;
	public static final long RING_STATS_BYTES = 0x30L;
	// enum LinkSideFlags
	public static final int SIDE_PEER_ALIVE = 0x1;
	public static final long SD_PROTOCOL_VERSION = 0x00L;
	public static final long SD_ATTACH_COUNT = 0x04L;
	public static final long SD_SESSION_NONCE = 0x08L;
	public static final long SD_ATTACH_NS = 0x10L;
	public static final long SD_UPDATE_COUNT = 0x18L;
	public static final long SD_PEER_DOWN_COUNT = 0x20L;
	public static final long SD_FLAGS = 0x24L;
	public static final long SD_TICK_MS = 0x28L;
	public static final long SD_FRAME_MS = 0x2CL;
	public static final long SD_OVERLAY_FRAMES = 0x30L;
	public static final long SD_RINGS = 0x40L;
	public static final long LINK_SIDE_STATS_BYTES = 0x100L;
	public static final long LS_HOST = 0x000L;
	public static final long LS_MC = 0x100L;
	public static final long LINK_STATS_BYTES = 0x200L;
	public static final long MC_NAME_BYTES = 24L;

	// ==== CLIENT LINK (GMod client <-> MC client) ====
	public static final long CL_OFF_HEADER = 0x0L;
	public static final long CL_OFF_HOST_STATE = 0x100L;
	public static final long CL_OFF_MC_STATE = 0x200L;
	public static final long CL_OFF_OVERLAY_CTL = 0x300L;
	public static final long CL_OFF_OVERLAY_SLOT_HDR = 0x340L;
	public static final long CL_OFF_WATER_GRID = 0x400L;
	public static final long CL_OFF_MC_IDENTITY = 0x880L;
	public static final long CL_OFF_LINK_STATS = 0xC00L;
	public static final long CL_OFF_INPUT_RING = 0x1000L;
	public static final long CL_OFF_ACTOR_TABLE = 0x12000L;
	public static final long CL_OFF_WORLD_ENTITIES = 0x17000L;
	public static final long CL_OFF_JOIN_INFO = 0x1B000L;
	public static final long CL_OFF_JOIN_STATUS = 0x1B200L;
	public static final long CL_OFF_EVENT_RING = 0x1C000L;
	public static final long CL_OFF_MC_SCREEN = 0x1F080L;
	public static final long CL_OFF_MC_SKY = 0x1F100L;
	public static final long CL_OFF_COLLISION_RING = 0x20000L;
	public static final long CL_COLLISION_RING_BYTES = 0x2000000L;
	public static final long CL_OFF_OVERLAY_PIXELS = 0x2020000L;
	public static final int MAX_OVERLAY_W = 3840;
	public static final int MAX_OVERLAY_H = 2160;
	public static final long OVERLAY_SLOT_BYTES = 0x1FA4000L;
	public static final int OVERLAY_SLOTS = 3;
	public static final long CL_OFF_RENDER_RING = 0x7F0C000L;
	public static final long RENDER_RING_BYTES = 0x4000000L;
	public static final long CL_MAPPING_BYTES = 0xBF0C000L;

	// host -> MC state @kClOffHostState (seqlock)
	// enum HostFlags
	public static final int HOST_IN_GAME = 0x1;
	public static final int HOST_MENU_OPEN = 0x2;
	public static final int HOST_LOADING = 0x4;
	public static final int HOST_SLOT_KNOWN = 0x8;
	// enum HostHybridFlags
	public static final int HOST_HYBRID = 0x1;
	public static final int HOST_WEAPON_ACTIVE = 0x2;
	// enum HostCarryFlags
	public static final int CARRY_ON_TOP = 0x1;
	public static final long HS_SEQ = 0x00L;
	public static final long HS_FLAGS = 0x04L;
	public static final long HS_WORLD_ID = 0x08L;
	public static final long HS_COLLISION_EPOCH = 0x0CL;
	public static final long HS_POS_X = 0x10L;
	public static final long HS_POS_Y = 0x18L;
	public static final long HS_POS_Z = 0x20L;
	public static final long HS_YAW = 0x28L;
	public static final long HS_PITCH = 0x2CL;
	public static final long HS_SLOT_ORIGIN_X = 0x30L;
	public static final long HS_SLOT_ORIGIN_Z = 0x34L;
	public static final long HS_VIEWPORT_W = 0x38L;
	public static final long HS_VIEWPORT_H = 0x3CL;
	public static final long HS_GAME_HOUR = 0x40L;
	public static final long HS_SLOT_ORIGIN_Y = 0x44L;
	public static final long HS_HYBRID_FLAGS = 0x48L;
	public static final long HS_CLIP1 = 0x4CL;
	public static final long HS_MAX_CLIP1 = 0x50L;
	public static final long HS_AMMO1 = 0x54L;
	public static final long HS_AMMO2 = 0x58L;
	public static final long HS_CARRY_ENT = 0x5CL;
	public static final long HS_CARRY_SEQ = 0x60L;
	public static final long HS_CARRY_FLAGS = 0x64L;
	public static final long HS_CARRY_VEL_X = 0x68L;
	public static final long HS_CARRY_VEL_Y = 0x6CL;
	public static final long HS_CARRY_VEL_Z = 0x70L;
	public static final long HS_CARRY_YAW_RATE = 0x74L;
	public static final long HS_CARRY_PIVOT_X = 0x78L;
	public static final long HS_CARRY_PIVOT_Y = 0x80L;
	public static final long HS_CARRY_PIVOT_Z = 0x88L;
	public static final long HS_CARRY_TOP_Y = 0x90L;
	public static final long HS_CARRY_YAW = 0x98L;
	public static final long HOST_STATE_BYTES = 0xA0L;

	// MC -> host state @kClOffMcState (seqlock)
	// enum McFlags
	public static final int MC_IN_WORLD = 0x1;
	public static final int MC_SCREEN_OPEN = 0x2;
	public static final int MC_ON_GROUND = 0x4;
	public static final int MC_SNEAKING = 0x8;
	public static final int MC_SPRINTING = 0x10;
	public static final int MC_DEAD = 0x20;
	public static final int MC_SWIMMING = 0x40;
	public static final int MC_FLYING = 0x80;
	public static final int MC_HELD = 0x100;
	public static final long MS_SEQ = 0x00L;
	public static final long MS_FLAGS = 0x04L;
	public static final long MS_X = 0x08L;
	public static final long MS_Y = 0x10L;
	public static final long MS_Z = 0x18L;
	public static final long MS_YAW = 0x20L;
	public static final long MS_PITCH = 0x24L;
	public static final long MS_EYE_HEIGHT = 0x28L;
	public static final long MS_SENSITIVITY = 0x2CL;
	public static final long MS_TELEPORT_COUNT = 0x30L;
	public static final long MS_GUI_SCALE = 0x34L;
	public static final long MS_FRAME_COUNTER = 0x38L;
	public static final long MS_FOV = 0x40L;
	public static final long MS_BOB_PHASE = 0x44L;
	public static final long MS_BOB_AMOUNT = 0x48L;
	public static final long MS_HELD_WEAPON = 0x4CL;
	public static final long MS_EYE_X = 0x50L;
	public static final long MS_EYE_Y = 0x58L;
	public static final long MS_EYE_Z = 0x60L;
	public static final long MS_TICK_NS = 0x68L;
	public static final long MS_PREV_X = 0x70L;
	public static final long MS_PREV_Y = 0x78L;
	public static final long MS_PREV_Z = 0x80L;
	public static final long MS_CUR_X = 0x88L;
	public static final long MS_CUR_Y = 0x90L;
	public static final long MS_CUR_Z = 0x98L;
	public static final long MS_EYE_HEIGHT_O = 0xA0L;
	public static final long MS_EYE_HEIGHT_T = 0xA4L;
	public static final long MS_WALK_O = 0xA8L;
	public static final long MS_WALK = 0xACL;
	public static final long MS_BOB_O = 0xB0L;
	public static final long MS_BOB = 0xB4L;
	public static final long MS_TICK_MS = 0xB8L;
	public static final long MS_CAMERA_MODE = 0xC0L;
	public static final long MS_CAMERA_DISTANCE = 0xC4L;
	public static final long MS_HELD_SLOT = 0xC8L;
	public static final long MS_CARRY_ENT = 0xCCL;
	public static final long MC_STATE_BYTES = 0xD0L;

	// overlay triple buffer @kClOffOverlayCtl
	public static final int OVERLAY_DIRTY = 0x4;
	// enum OverlayFlags
	public static final int OV_BOTTOM_UP = 0x1;
	public static final int OV_BGRA = 0x2;
	public static final int OV_SRGB_ENCODED = 0x4;
	public static final long OC_STATE = 0x00L;
	public static final long OC_FRAMES_PUBLISHED = 0x08L;
	public static final long SH_WIDTH = 0x00L;
	public static final long SH_HEIGHT = 0x04L;
	public static final long SH_FLAGS = 0x08L;
	public static final long SH_FRAME_ID = 0x10L;
	public static final long SLOT_HDR_BYTES = 0x40L;

	// MC identity @kClOffMcIdentity (MC client -> host, seqlock)
	// enum McIdentityFlags
	public static final int ID_IN_WORLD = 0x1;
	public static final int ID_ONLINE_ACCOUNT = 0x2;
	public static final int ID_INTEGRATED_SERVER = 0x4;
	public static final long ID_SEQ = 0x00L;
	public static final long ID_FLAGS = 0x04L;
	public static final long ID_UUID = 0x08L;
	public static final long ID_NAME = 0x18L;
	public static final long MC_IDENTITY_BYTES = 0x30L;


	// input ring @kClOffInputRing (host produces, MC consumes)
	public static final int INPUT_RING_ENTRIES = 4096;
	public static final long IR_HEAD = 0x00L;
	public static final long IR_TAIL = 0x40L;
	public static final long IR_DATA = 0x80L;
	// enum InputType
	public static final int IN_KEY = 1;
	public static final int IN_MOUSE_BUTTON = 2;
	public static final int IN_SCROLL = 3;
	public static final int IN_CURSOR = 4;
	public static final int IN_TEXT = 5;
	public static final int IN_RELEASE_ALL = 6;
	public static final int IN_OPEN_MENU = 8;
	public static final long INPUT_EVENT_BYTES = 16L;
	public static final long INPUT_RING_BYTES = 0x10080L;

	// world entities @kClOffWorldEntities (MC -> host, seqlock)
	public static final int MAX_WORLD_ENTITIES = 160;
	// enum WorldEntityKind
	public static final int WE_ARROW = 1;
	public static final int WE_ITEM = 2;
	public static final int WE_TRIDENT = 3;
	public static final int WE_BLOCK = 4;
	public static final int WE_CRACK = 5;
	public static final int WE_SHADOW = 6;
	public static final long WORLD_ENTITY_BYTES = 96L;
	public static final long WT_SEQ = 0x00L;
	public static final long WT_COUNT = 0x04L;
	public static final long WT_HAS_SELECTION = 0x08L;
	public static final long WT_SEL_MIN = 0x0CL;
	public static final long WT_SEL_MAX = 0x18L;
	public static final long WT_RECORDS = 0x40L;
	public static final long WORLD_ENTITIES_BYTES = 0x3C40L;

	// join info @kClOffJoinInfo (host -> MC, seqlock)
	public static final long SERVER_ADDRESS_BYTES = 256L;
	public static final long JOIN_TOKEN_BYTES = 128L;
	public static final long JI_SEQ = 0x00L;
	public static final long JI_FLAGS = 0x04L;
	public static final long JI_SERVER_ADDRESS = 0x08L;
	public static final long JI_JOIN_TOKEN = 0x108L;
	public static final long JI_JOIN_ID = 0x188L;
	public static final long JOIN_INFO_BYTES = 0x190L;

	// join status @kClOffJoinStatus (MC -> host, seqlock)
	// enum JoinState
	public static final int JOIN_STATE_OWN_WORLD = 0;
	public static final int JOIN_STATE_CONNECTING = 1;
	public static final int JOIN_STATE_JOINED = 2;
	// enum JoinResult
	public static final int JOIN_OK = 0;
	public static final int JOIN_FAILED = 1;
	public static final int JOIN_LEFT = 2;
	public static final int JOIN_LOST = 3;
	public static final int JOIN_BAD_ADDRESS = 4;
	public static final long JOIN_REASON_BYTES = 256L;
	public static final long JS_SEQ = 0x00L;
	public static final long JS_STATE = 0x04L;
	public static final long JS_JOIN_ID = 0x08L;
	public static final long JS_RESULT = 0x0CL;
	public static final long JS_SERVER_ADDRESS = 0x10L;
	public static final long JS_REASON = 0x110L;
	public static final long JOIN_STATUS_BYTES = 0x210L;

	// MC -> host: the open screen @kClOffMcScreen (seqlock; v35, S1)
	// enum McScreenFlags
	public static final int SCR_OPEN = 0x1;
	public static final int SCR_CONTAINER = 0x2;
	public static final long SCR_SEQ = 0x00L;
	public static final long SCR_FLAGS = 0x04L;
	public static final long SCR_HOVERED_SLOT = 0x08L;
	public static final long SCR_CURSOR_X = 0x0CL;
	public static final long SCR_CURSOR_Y = 0x10L;
	public static final long SCR_FRAME_COUNTER = 0x18L;
	public static final long MC_SCREEN_BYTES = 0x40L;

	// MC -> host: the sky @kClOffMcSky (seqlock; v37, K1)
	// enum McSkyFlags
	public static final int MSK_VALID = 0x1;
	public static final int MSK_OVERWORLD = 0x2;
	public static final int MSK_END = 0x4;
	public static final long MSK_SEQ = 0x00L;
	public static final long MSK_FLAGS = 0x04L;
	public static final long MSK_SUN_ANGLE = 0x08L;
	public static final long MSK_MOON_ANGLE = 0x0CL;
	public static final long MSK_STAR_ANGLE = 0x10L;
	public static final long MSK_RAIN_BRIGHTNESS = 0x14L;
	public static final long MSK_STAR_BRIGHTNESS = 0x18L;
	public static final long MSK_MOON_PHASE = 0x1CL;
	public static final long MSK_SKY = 0x20L;
	public static final long MSK_FOG = 0x2CL;
	public static final long MSK_SUNRISE = 0x38L;
	public static final long MSK_FRAME_COUNTER = 0x48L;
	public static final long MC_SKY_BYTES = 0x70L;

	// client event ring @kClOffEventRing (MC client produces, host consumes; v14)
	public static final int CL_EVENT_RING_ENTRIES = 256;
	public static final long CL_EVENT_RING_BYTES = 0x3080L;

	// render ring @kClOffRenderRing (MC -> host)
	public static final long RR_HEAD = 0x00L;
	public static final long RR_TAIL = 0x40L;
	public static final long RR_DATA = 0x80L;
	// enum RenType
	public static final int REN_PAD = 0;
	public static final int REN_ATLAS = 1;
	public static final int REN_SECTION = 2;
	public static final int REN_CLEAR_ALL = 3;
	public static final int REN_TEXTURE = 4;
	public static final int REN_AVATAR = 5;
	public static final int REN_SCENE = 6;
	public static final int REN_ATLAS_REGION = 7;
	public static final int REN_LIGHTS = 8;
	public static final int REN_RAGDOLL = 9;
	public static final int REN_SOLIDS = 10;
	public static final int REN_DUG = 11;
	// enum RagdollPart
	public static final int PART_NONE = 0;
	public static final int PART_HEAD = 1;
	public static final int PART_BODY = 2;
	public static final int PART_RIGHT_ARM = 3;
	public static final int PART_LEFT_ARM = 4;
	public static final int PART_RIGHT_LEG = 5;
	public static final int PART_LEFT_LEG = 6;
	public static final int PART_COUNT = 7;
	// enum LightKind
	public static final int LIGHT_STEADY = 0;
	public static final int LIGHT_FLAME = 1;
	public static final int LIGHT_LAVA = 2;
	// enum BlockHazard
	public static final int HAZARD_NONE = 0;
	public static final int HAZARD_FIRE = 1;
	public static final int HAZARD_LAVA = 2;
	public static final int HAZARD_MAGMA = 3;
	// enum RenPixelFlags
	public static final int REN_PIX_BGRA = 0x1;
	public static final int REN_VERTEX_BYTES = 32;


	// ==== SERVER LINK (GMod server <-> MC server) ====
	public static final long SV_OFF_HEADER = 0x0L;
	public static final long SV_OFF_SERVER_STATE = 0x100L;
	public static final long SV_OFF_MC_SERVER_STATE = 0x200L;
	public static final long SV_OFF_MC_SERVER_SKY = 0x240L;
	public static final long SV_OFF_WATER_GRID = 0x400L;
	public static final long SV_OFF_LINK_STATS = 0xC00L;
	public static final long SV_OFF_HOST_EVENT_RING = 0x1000L;
	public static final long SV_OFF_HOST_PLAYERS = 0x12000L;
	public static final long SV_OFF_MC_PLAYERS = 0x15000L;
	public static final long SV_OFF_ACTOR_TABLE = 0x18000L;
	public static final long SV_OFF_EVENT_RING = 0x1D000L;
	public static final long SV_OFF_MC_SERVER_INFO = 0x2A000L;
	public static final long SV_OFF_HELD_MC_ENTITIES = 0x2B000L;
	public static final long SV_OFF_MC_WEAPON_SETS = 0x30000L;
	public static final long SV_OFF_MC_ENTITIES = 0x3B800L;
	public static final long SV_OFF_BLOCK_RING = 0x40000L;
	public static final long SV_BLOCK_RING_BYTES = 0x100000L;
	public static final long SV_OFF_COLLISION_RING = 0x140000L;
	public static final long SV_COLLISION_RING_BYTES = 0x2000000L;
	public static final long SV_OFF_WATER_GRIDS = 0x2140000L;
	public static final long SV_WATER_GRIDS_BYTES = 0x21000L;
	public static final long SV_MAPPING_BYTES = 0x2161000L;

	// host -> MC server state @kSvOffServerState (seqlock)
	// enum ServerFlags
	public static final int SERVER_IN_GAME = 0x1;
	public static final int SERVER_LOADING = 0x2;
	public static final int SERVER_WIREMOD = 0x4;
	public static final int SERVER_MAP_IO = 0x10;
	public static final int SERVER_ANCHOR_READY = 0x8;
	// enum AnchorSource
	public static final int ANCHOR_NONE = 0;
	public static final int ANCHOR_SPAWNS = 1;
	public static final int ANCHOR_MAP_MODE = 2;
	public static final int ANCHOR_CURATED = 3;
	public static final int ANCHOR_OPERATOR = 4;
	public static final int ANCHOR_FORCED = 5;
	public static final int ANCHOR_LEGACY = 6;
	public static final int ANCHOR_TIMEOUT = 7;
	public static final long MAP_NAME_BYTES = 40L;
	public static final long SS_SEQ = 0x00L;
	public static final long SS_FLAGS = 0x04L;
	public static final long SS_WORLD_ID = 0x08L;
	public static final long SS_COLLISION_EPOCH = 0x0CL;
	public static final long SS_TICK_NS = 0x10L;
	public static final long SS_MAP_NAME = 0x18L;
	public static final long SS_ANCHOR_SOURCE = 0x40L;
	public static final long SS_FLOOR_Z = 0x44L;
	public static final long SS_MIN_Z = 0x48L;
	public static final long SS_MAX_Z = 0x4CL;
	public static final long SS_FOOT_MIN_X = 0x50L;
	public static final long SS_FOOT_MIN_Y = 0x54L;
	public static final long SS_FOOT_MAX_X = 0x58L;
	public static final long SS_FOOT_MAX_Y = 0x5CL;
	public static final long SS_SUN_SYNC = 0x60L;
	public static final long SERVER_STATE_BYTES = 0x80L;

	// MC server -> host state @kSvOffMcServerState (seqlock)
	// enum McServerFlags
	public static final int MC_SRV_SLOT_VALID = 0x1;
	public static final int MC_SRV_DEDICATED = 0x2;
	public static final int MC_SRV_NEW_SLOT = 0x4;
	public static final int MC_SRV_SLOT_BUSY = 0x8;
	public static final int MC_SRV_ANCHOR_WAIT = 0x10;
	public static final long MSS_SEQ = 0x00L;
	public static final long MSS_FLAGS = 0x04L;
	public static final long MSS_WORLD_ID = 0x08L;
	public static final long MSS_SLOT_X = 0x0CL;
	public static final long MSS_SLOT_Z = 0x10L;
	public static final long MSS_ORIGIN_X = 0x14L;
	public static final long MSS_ORIGIN_Z = 0x18L;
	public static final long MSS_SLOT_COUNT = 0x1CL;
	public static final long MSS_TICK_NS = 0x20L;
	public static final long MSS_ORIGIN_Y = 0x28L;
	public static final long MSS_ANCHOR_SOURCE = 0x2CL;
	public static final long MSS_RULE_FLAGS = 0x30L;
	public static final long MSS_GAME_MODE = 0x34L;
	public static final long MSS_WORLD_TYPE = 0x35L;
	public static final long MSS_FLOOR_Y = 0x36L;
	public static final long MSS_DAMAGE_SCALE = 0x38L;
	public static final long MSS_DIFFICULTY = 0x3CL;
	public static final long MSS_MOB_CAP_PERCENT = 0x3EL;
	public static final long MC_SERVER_STATE_BYTES = 0x40L;
	// enum SunSyncMode
	public static final int SUN_SYNC_OFF = 0;
	public static final int SUN_SYNC_MC_TO_GMOD = 1;
	public static final int SUN_SYNC_GMOD_TO_MC = 2;

	// MC server -> host: the overworld's time of day @kSvOffMcServerSky (seqlock; v43)
	// enum McServerSkyFlags
	public static final int MSV_SKY_VALID = 0x1;
	public static final int MSV_SKY_ADVANCING = 0x2;
	public static final long MSV_SEQ = 0x00L;
	public static final long MSV_FLAGS = 0x04L;
	public static final long MSV_DAY_TIME = 0x08L;
	public static final long MSV_SUN_ANGLE = 0x10L;
	public static final long MSV_MOON_ANGLE = 0x14L;
	public static final long MSV_STAR_BRIGHTNESS = 0x18L;
	public static final long MSV_SKY_LIGHT = 0x1CL;
	public static final long MSV_MOON_PHASE = 0x20L;
	public static final long MSV_RATE = 0x24L;
	public static final long MSV_SKY = 0x28L;
	public static final long MSV_FOG = 0x34L;
	public static final long MSV_SUNRISE = 0x40L;
	public static final long MSV_TICK_NS = 0x50L;
	public static final long MC_SERVER_SKY_BYTES = 0x80L;
	// enum ServerRuleFlags
	public static final int RULES_VALID = 0x1;
	public static final int RULE_FORCE_GAMEMODE = 0x2;
	public static final int RULE_PVP = 0x4;
	public static final int RULE_KEEP_INVENTORY = 0x8;
	public static final int RULE_DIG_INTO_MAP = 0x10;
	public static final int RULE_NOCLIP_MC = 0x20;
	public static final int RULE_FIRE_CROSSOVER = 0x40;
	public static final int RULE_PHYSGUN_MOBS = 0x80;
	public static final int RULE_MOB_SPAWNING = 0x100;
	public static final int RULE_DIG_THIN_WALLS = 0x200;
	// enum DifficultyId
	public static final int DIFFICULTY_PEACEFUL = 0;
	public static final int DIFFICULTY_EASY = 1;
	public static final int DIFFICULTY_NORMAL = 2;
	public static final int DIFFICULTY_HARD = 3;
	public static final int MOB_CAP_MAX = 1000;
	// enum GameModeId
	public static final int GAME_SURVIVAL = 0;
	public static final int GAME_CREATIVE = 1;
	public static final int GAME_ADVENTURE = 2;
	public static final int GAME_SPECTATOR = 3;
	// enum WorldType
	public static final int WORLD_VOID = 0;
	public static final int WORLD_FLAT_VOID_MAPS = 1;
	public static final int WORLD_FLAT_EVERYWHERE = 2;
	public static final int WORLD_OTHER = 3;
	public static final int WORLD_UNDERGROUND = 4;
	public static final int WORLD_HULL = 5;
	public static final int FLAT_LAYERS = 4;

	// MC server info @kSvOffMcServerInfo (MC server -> host, seqlock; v14)
	// enum McServerInfoFlags
	public static final int SRV_INFO_OPEN = 0x1;
	public static final int SRV_INFO_DEDICATED = 0x2;
	public static final int SRV_INFO_ONLINE_MODE = 0x4;
	public static final int SRV_INFO_E4MC_INSTALLED = 0x8;
	public static final int SRV_INFO_E4MC_READY = 0x10;
	public static final long SERVER_INFO_ADDRESS_BYTES = 128L;
	public static final long SI_SEQ = 0x00L;
	public static final long SI_FLAGS = 0x04L;
	public static final long SI_PORT = 0x08L;
	public static final long SI_REQUEST_ID = 0x0CL;
	public static final long SI_MAX_PLAYERS = 0x10L;
	public static final long SI_LAN_ADDRESS = 0x18L;
	public static final long SI_E4MC_ADDRESS = 0x98L;
	public static final long MC_SERVER_INFO_BYTES = 0x118L;



	// host event ring @kSvOffHostEventRing (host produces, MC server consumes)
	public static final int HOST_EVENT_RING_ENTRIES = 1024;
	public static final int TELEPORT_ACK_TIMEOUT_MS = 5000;
	public static final long HR_HEAD = 0x00L;
	public static final long HR_TAIL = 0x40L;
	public static final long HR_DATA = 0x80L;
	// enum HostEventType
	public static final int HOST_EV_HURT = 1;
	public static final int HOST_EV_TELEPORT = 2;
	public static final int HOST_EV_RESPAWN = 3;
	public static final int HOST_EV_OPEN_TO_LAN = 4;
	public static final int HOST_EV_DEV_COMMAND = 5;
	public static final int HOST_EV_DEV_COMMAND_TEXT = 6;
	public static final int HOST_EV_BRIDGE_OUTPUTS = 7;
	public static final int HOST_EV_WEAPON_GIVE = 8;
	public static final int HOST_EV_WEAPON_TEXT = 9;
	public static final int HOST_EV_WEAPON_TAKE = 10;
	public static final int HOST_EV_WEAPON_STATE = 11;
	public static final int HOST_EV_ADMIN_COMMAND = 12;
	public static final int HOST_EV_ADMIN_TEXT = 13;
	public static final int HOST_EV_HURT_MC_ENTITY = 14;
	public static final int HOST_EV_FIRE = 15;
	public static final int HOST_EV_PUNT_MC_ENTITY = 16;
	public static final int HOST_EV_PROP_RESULT = 19;
	public static final int HOST_EV_PROP_TEXT = 20;
	public static final int HOST_EV_SET_DAY_TIME = 21;
	public static final int HOST_EV_PULL_BLOCK = 22;
	public static final int HOST_EV_BLAST = 23;
	public static final int HOST_EV_SELECT_WEAPON = 24;
	// enum DayTimeFlags
	public static final int DAY_TIME_SET = 0x1;
	public static final int TICKS_PER_DAY = 24000;
	public static final int DAY_TIME_MAX_RATE = 1000;
	// enum PullFlags
	public static final int PULL_BY_ADMIN = 0x1;
	public static final int BLAST_MAX_POWER = 6;
	public static final int BLASTS_PER_TICK = 4;
	// enum AdminCommand
	public static final int ADMIN_DEMO_PLACE = 1;
	public static final int ADMIN_DEMO_CLEAR = 2;
	public static final int ADMIN_DEMO_CLEAR_ALL = 3;
	public static final int ADMIN_DEMO_ANNOUNCE = 4;
	public static final int ADMIN_REPAIR_RADIUS = 5;
	public static final int ADMIN_REPAIR_COLUMN = 6;
	public static final int ADMIN_REPAIR_UNDO = 7;
	public static final int ADMIN_BLOCK_PLACE = 8;
	public static final int ADMIN_BLOCK_BREAK = 9;
	public static final int ADMIN_BLOCK_UNDO = 10;
	public static final int ADMIN_RESYNC = 11;
	public static final int ADMIN_REANCHOR = 12;
	public static final int ADMIN_REANCHOR_UNDO = 13;
	public static final int ADMIN_SET_RULES = 14;
	public static final int ADMIN_SLOT_HASH = 15;
	public static final int ADMIN_SLOT_HISTORY = 16;
	public static final int ADMIN_BRIDGE_LINK = 17;
	public static final int ADMIN_SLOT_INFO = 18;
	public static final int ADMIN_WORLD_LIST = 19;
	public static final int ADMIN_WORLD_OP = 20;
	public static final int ADMIN_STRUCT_EXPORT = 21;
	// enum WorldListKind
	public static final int WORLD_ENTRY_RUNNING = 0;
	public static final int WORLD_ENTRY_BACKUP = 1;
	// enum WorldOp
	public static final int WORLD_OP_NONE = 0;
	public static final int WORLD_OP_NEW = 1;
	public static final int WORLD_OP_RESTORE = 2;
	public static final int WORLD_OP_CANCEL = 3;
	// enum AdminFlags
	public static final int ADMIN_FORCE = 0x1;
	public static final int ADMIN_ALLOW_LIQUID = 0x2;
	public static final int ADMIN_BY_ADMIN = 0x4;
	public static final int ADMIN_EVERYONE = 0x8;
	public static final int ADMIN_DRY_RUN = 0x10;
	public static final int ADMIN_STAGED = 0x20;
	public static final int ADMIN_RESTART_NOW = 0x40;
	public static final int ADMIN_TEXT_BYTES = 60;
	public static final int STRUCT_MAX_EDGE = 32;
	public static final int STRUCT_TEXT_MAX_BYTES = 262144;
	public static final int STRUCT_CHUNK_BYTES = 44;
	public static final int STRUCT_MAX_CHUNKS = 16;
	public static final int RULES_STAGE_MS = 5000;
	public static final int WEAPON_TEXT_CHUNK_BYTES = 60;
	public static final int WEAPON_TEXT_MAX_CHUNKS = 3;
	public static final int WEAPON_TEXT_MAX_BYTES = 180;
	public static final int WEAPON_CLASS_MAX_BYTES = 64;
	// enum WeaponCategory
	public static final int WEAP_CAT_GENERIC = 0;
	public static final int WEAP_CAT_PISTOL = 1;
	public static final int WEAP_CAT_SMG = 2;
	public static final int WEAP_CAT_RIFLE = 3;
	public static final int WEAP_CAT_SHOTGUN = 4;
	public static final int WEAP_CAT_HEAVY = 5;
	public static final int WEAP_CAT_MELEE = 6;
	public static final int WEAP_CAT_TOOL = 7;
	public static final int WEAP_CATEGORIES = 8;
	// enum PropOp
	public static final int PROP_OP_PICKUP = 1;
	public static final int PROP_OP_PLACE = 2;
	// enum PropResult
	public static final int PROP_OK = 0;
	public static final int PROP_NOT_ALLOWED = 1;
	public static final int PROP_LIMIT = 2;
	public static final int PROP_NOT_A_PROP = 3;
	public static final int PROP_CONSTRAINED = 4;
	public static final int PROP_DISABLED = 5;
	public static final int PROP_MALFORMED = 6;
	public static final int PROP_FAILED = 7;
	public static final int PROP_MODEL_MAX_BYTES = 260;
	public static final int PROP_MATERIAL_MAX_BYTES = 96;
	public static final int PROP_BODYGROUPS_MAX_BYTES = 32;
	public static final int PROP_DUPE_MAX_BYTES = 16;
	public static final int PROP_TEXT_MAX_BYTES = 440;
	public static final int PROP_HOST_CHUNK_BYTES = 60;
	public static final int PROP_HOST_MAX_CHUNKS = 8;
	public static final int PROP_MC_CHUNK_BYTES = 44;
	public static final int PROP_MC_MAX_CHUNKS = 10;
	public static final int PROP_MAX_STACK = 16;
	public static final int PROP_SKIN_SHIFT = 16;
	public static final long HE_TEXT = 0x04L;
	public static final int DEV_COMMAND_CHUNK_BYTES = 60;
	public static final int DEV_COMMAND_MAX_CHUNKS = 4;
	public static final int DEV_COMMAND_MAX_BYTES = 240;
	// enum OpenFlags
	public static final int OPEN_ALLOW_OFFLINE = 0x1;
	// enum HurtKind
	public static final int HURT_MELEE = 0;
	public static final int HURT_PROJECTILE = 1;
	public static final int HURT_MAGIC = 2;
	public static final int HURT_OTHER = 3;
	// enum HurtFlags
	public static final int HURT_BLOCKED_BY_HOST = 0x1;
	public static final int HURT_POWER_ATTACK = 0x2;
	public static final int HURT_FIRE = 0x4;
	// enum TeleportReason
	public static final int TELEPORT_REASON_SET_POS = 0;
	public static final int TELEPORT_REASON_SPAWN = 1;
	public static final int TELEPORT_REASON_MAP_CHANGE = 2;
	public static final int TELEPORT_REASON_VEHICLE = 3;
	// enum TeleportFlags
	public static final int TELEPORT_KEEP_LOOK = 0x1;
	public static final long HE_TYPE = 0x00L;
	public static final long HE_CODE = 0x02L;
	public static final long HE_ENT_ID = 0x04L;
	public static final long HE_STEAM_ID = 0x08L;
	public static final long HE_REQUEST_ID = 0x10L;
	public static final long HE_FLAGS = 0x14L;
	public static final long HE_A = 0x18L;
	public static final long HE_WORLD_ID = 0x1CL;
	public static final long HE_X = 0x20L;
	public static final long HE_Y = 0x28L;
	public static final long HE_Z = 0x30L;
	public static final long HE_YAW = 0x38L;
	public static final long HE_PITCH = 0x3CL;
	public static final long HOST_EVENT_BYTES = 64L;
	public static final long HOST_EVENT_RING_BYTES = 0x10080L;

	// player map
	public static final int MAX_PLAYERS = 128;
	// enum HostPlayerFlags
	public static final int HOST_PLAYER_ALIVE = 0x1;
	public static final int HOST_PLAYER_BOT = 0x2;
	public static final int HOST_PLAYER_HAS_MC = 0x4;
	public static final int HOST_PLAYER_NOCLIP = 0x8;
	public static final int HOST_PLAYER_CARRIED = 0x10;
	public static final long HP_STEAM_ID = 0x00L;
	public static final long HP_ENT_INDEX = 0x08L;
	public static final long HP_FLAGS = 0x0CL;
	public static final long HP_MC_UUID = 0x10L;
	public static final long HP_MC_NAME = 0x20L;
	public static final long HOST_PLAYER_BYTES = 64L;
	public static final long PT_SEQ = 0x00L;
	public static final long PT_COUNT = 0x04L;
	public static final long PT_RECORDS = 0x40L;
	public static final long HOST_PLAYERS_BYTES = 0x2040L;
	// enum McPlayerFlags
	public static final int MC_PLAYER_DEAD = 0x1;
	public static final int MC_PLAYER_MAPPED = 0x2;
	public static final int MC_PLAYER_HELD = 0x4;
	public static final int MC_PLAYER_IN_WATER = 0x8;
	public static final long MP_UUID = 0x00L;
	public static final long MP_STEAM_ID = 0x10L;
	public static final long MP_ENTITY_ID = 0x18L;
	public static final long MP_FLAGS = 0x1CL;
	public static final long MP_HEALTH = 0x20L;
	public static final long MP_MAX_HEALTH = 0x24L;
	public static final long MP_NAME = 0x28L;
	public static final long MC_PLAYER_BYTES = 64L;
	public static final long MC_PLAYERS_BYTES = 0x2040L;

	// weapon sets @kSvOffMcWeaponSets (MC server -> host; v17 hybrid mode)
	public static final int MAX_WEAPONS_PER_PLAYER = 40;
	public static final long WE_HASH = 0x00L;
	public static final long WE_CLIP1 = 0x04L;
	public static final long WEAPON_ENTRY_BYTES = 8L;
	// enum McWeaponSetFlags
	public static final int WEAPON_SET_DEAD = 0x1;
	public static final long WS_SEQ = 0x00L;
	public static final long WS_COUNT = 0x04L;
	public static final long WS_HELD_HASH = 0x08L;
	public static final long WS_LAST_REQUEST_ID = 0x0CL;
	public static final long WS_STEAM_ID = 0x10L;
	public static final long WS_FLAGS = 0x18L;
	public static final long WS_ENTRIES = 0x20L;
	public static final long MC_WEAPON_SET_BYTES = 0x160L;
	public static final long WTS_COUNT = 0x04L;
	public static final long WTS_SETS = 0x40L;
	public static final long MC_WEAPON_SETS_BYTES = 0xB040L;

	// MC entities @kSvOffMcEntities (MC server -> host, seqlock; v27)
	public static final int MAX_MC_ENTITIES = 256;
	public static final int MC_ENTITY_RANGE = 64;
	// enum McEntityCategory
	public static final int MC_ENT_OTHER = 0;
	public static final int MC_ENT_HOSTILE = 1;
	public static final int MC_ENT_PASSIVE = 2;
	public static final int MC_ENT_VEHICLE = 3;
	public static final int MC_ENT_FALLING_BLOCK = 4;
	public static final int MC_ENT_TNT = 5;
	public static final int MC_ENT_CATEGORY_MASK = 0xF;
	public static final int MC_ENT_YAW_SHIFT = 6;
	public static final int MC_ENT_YAW_STEPS = 1024;
	// enum McEntityFlags
	public static final int MC_ENT_DEAD = 0x1;
	public static final long MEN_ENTITY_ID = 0x00L;
	public static final long MEN_CATEGORY = 0x04L;
	public static final long MEN_FLAGS = 0x06L;
	public static final long MEN_TYPE_HASH = 0x08L;
	public static final long MEN_WIDTH = 0x0CL;
	public static final long MEN_X = 0x10L;
	public static final long MEN_Y = 0x18L;
	public static final long MEN_Z = 0x20L;
	public static final long MEN_VX = 0x28L;
	public static final long MEN_VY = 0x2CL;
	public static final long MEN_VZ = 0x30L;
	public static final long MEN_HEALTH = 0x34L;
	public static final long MEN_MAX_HEALTH = 0x38L;
	public static final long MEN_HEIGHT = 0x3CL;
	public static final long MC_ENTITY_BYTES = 0x40L;
	public static final long MC_ENTITIES_BYTES = 0x4040L;

	// held MC entities @kSvOffHeldMcEntities (host -> MC server, seqlock; v29)
	public static final int MAX_HELD_MC_ENTITIES = 64;
	public static final int HELD_STALE_MS = 1000;
	// enum HeldMcEntityFlags
	public static final int HELD_BY_PHYSGUN = 0x1;
	public static final int HELD_FROZEN = 0x2;
	public static final int HELD_CONSTRAINED = 0x4;
	public static final int HELD_PHYSICS = 0x8;
	public static final long HME_ENTITY_ID = 0x00L;
	public static final long HME_FLAGS = 0x04L;
	public static final long HME_HOLDER_STEAM_ID = 0x08L;
	public static final long HME_X = 0x10L;
	public static final long HME_Y = 0x18L;
	public static final long HME_Z = 0x20L;
	public static final long HME_VX = 0x28L;
	public static final long HME_VY = 0x2CL;
	public static final long HME_VZ = 0x30L;
	public static final long HME_YAW = 0x34L;
	public static final long HME_PITCH = 0x38L;
	public static final long HELD_MC_ENTITY_BYTES = 0x40L;
	public static final long HELD_MC_ENTITIES_BYTES = 0x1040L;

	// event ring @kSvOffEventRing (MC server -> host)
	public static final int EVENT_RING_ENTRIES = 1024;
	public static final long ER_HEAD = 0x00L;
	public static final long ER_TAIL = 0x40L;
	public static final long ER_DATA = 0x80L;
	// enum McEventType
	public static final int EV_HIT_ACTOR = 1;
	public static final int EV_PLAYER_DIED = 2;
	public static final int EV_EXPLOSION = 3;
	public static final int EV_ARROW_STUCK = 4;
	public static final int EV_TELEPORT_ACK = 6;
	public static final int EV_PLAYER_RESPAWNED = 7;
	public static final int EV_WORLD_OPENED = 8;
	public static final int EV_JOIN_RESULT = 9;
	public static final int EV_DEV_COMMAND_RESULT = 10;
	public static final int EV_DEV_COMMAND_TEXT = 11;
	public static final int EV_PROJECTILE_HIT = 12;
	public static final int EV_BRIDGE_PLACED = 13;
	public static final int EV_BRIDGE_REMOVED = 14;
	public static final int EV_BRIDGE_INPUTS = 15;
	public static final int EV_ADMIN_RESULT = 16;
	public static final int EV_DEMO_PLACED = 17;
	public static final int EV_DEMO_CLEARED = 18;
	public static final int EV_DEMO_SYNC_DONE = 19;
	public static final int EV_BRIDGE_LINK = 20;
	public static final int EV_FIRE_CONTACT = 21;
	public static final int EV_PROP_REQUEST = 24;
	public static final int EV_PROP_TEXT = 25;
	public static final int EV_STRUCT_DATA = 26;
	public static final int EV_STRUCT_TEXT = 27;
	public static final int EV_PISTON_MOVE = 28;
	public static final int FIRE_CONTACTS_PER_SCAN = 8;
	// enum PistonMoveFlags
	public static final int PISTON_DIR_MASK = 0x7;
	public static final int PISTON_EXTENDING = 0x8;
	public static final int PISTON_HEAD = 0x10;
	public static final int PISTON_TRAVEL_TICKS = 2;
	public static final int PISTON_EVENTS_PER_TICK = 128;
	// enum AdminResult
	public static final int ADMIN_OK = 0;
	public static final int ADMIN_OCCUPIED = 1;
	public static final int ADMIN_UNKNOWN_DEMO = 2;
	public static final int ADMIN_OUTSIDE_SLOT = 3;
	public static final int ADMIN_NO_INSTANCE = 4;
	public static final int ADMIN_MALFORMED = 5;
	public static final int ADMIN_FAILED = 6;
	public static final int ADMIN_NOT_ALLOWED = 7;
	public static final int ADMIN_NOTHING = 8;
	public static final int ADMIN_BAD_BLOCK = 9;
	public static final int ADMIN_LIQUID = 10;
	public static final int ADMIN_BUSY = 11;
	public static final int ADMIN_OUT_OF_RANGE = 12;
	public static final int ADMIN_SLOT_OCCUPIED = 13;
	public static final int ADMIN_BAD_RULE = 14;
	public static final int ADMIN_UNSUPPORTED = 15;
	// enum DemoKind
	public static final int DEMO_RAILS = 1;
	public static final int DEMO_REDSTONE = 2;
	public static final int DEMO_RANGE = 3;
	public static final int DEMO_RAMP = 4;
	public static final int DEMO_ARENA = 5;
	public static final int DEMO_DIG_WALL = 6;
	public static final int DEMO_PISTON = 7;
	public static final int DEMO_MAX_X = 32;
	public static final int DEMO_MAX_Y = 16;
	public static final int DEMO_MAX_Z = 32;
	// enum BridgeFace
	public static final int FACE_DOWN = 0;
	public static final int FACE_UP = 1;
	public static final int FACE_NORTH = 2;
	public static final int FACE_SOUTH = 3;
	public static final int FACE_WEST = 4;
	public static final int FACE_EAST = 5;
	public static final int BRIDGE_FACES = 6;
	// enum BridgeLinkKind
	public static final int LINK_BUTTON = 1;
	public static final int LINK_MOMENTARY = 2;
	public static final int LINK_TRIGGER = 3;
	public static final int LINK_DOOR = 4;
	public static final int LINK_MOVE_LINEAR = 5;
	public static final int LINK_RELAY = 6;
	public static final int LINK_LIGHT = 7;
	public static final int LINK_SPRITE = 8;
	// enum BridgeLinkMode
	public static final int LINK_IN = 1;
	public static final int LINK_OUT = 2;
	public static final int BRIDGE_LEVEL_BITS = 4;
	// enum ProjectileKind
	public static final int PROJ_ARROW = 1;
	public static final int PROJ_SPECTRAL_ARROW = 2;
	public static final int PROJ_TIPPED_ARROW = 3;
	public static final int PROJ_TRIDENT = 4;
	public static final int PROJ_SNOWBALL = 5;
	public static final int PROJ_EGG = 6;
	public static final int PROJ_THROWN = 7;
	public static final int PROJ_SMALL_FIREBALL = 8;
	public static final int PROJ_ON_FIRE = 0x100;
	public static final int PROJ_KIND_MASK = 0xFF;
	// enum FireCause
	public static final int FIRE_BURNING = 1;
	public static final int FIRE_EXPLOSION = 2;
	public static final int FIRE_BLOCKS_PER_EVENT = 3;
	public static final int FIRE_BLOCKS_PER_TICK = 6;
	// enum DevCommandResult
	public static final int DEV_COMMAND_OK = 0;
	public static final int DEV_COMMAND_FAILED = 1;
	public static final int DEV_COMMAND_DISABLED = 2;
	public static final int DEV_COMMAND_MALFORMED = 3;
	public static final long ME_TEXT = 0x04L;
	public static final int DEV_OUTPUT_CHUNK_BYTES = 44;
	public static final int DEV_OUTPUT_MAX_CHUNKS = 3;
	public static final int DEV_OUTPUT_MAX_BYTES = 132;
	// enum OpenResult
	public static final int OPEN_OK = 0;
	public static final int OPEN_FAILED = 1;
	public static final int OPEN_ALREADY_OPEN = 2;
	// enum TeleportResult
	public static final int TELEPORT_OK = 0;
	public static final int TELEPORT_NO_PLAYER = 1;
	public static final int TELEPORT_TIMEOUT = 2;
	public static final int TELEPORT_WRONG_WORLD = 3;
	public static final int TELEPORT_BAD_POSITION = 4;
	// enum HitFlags
	public static final int HIT_CRITICAL = 0x1;
	public static final int HIT_PROJECTILE = 0x2;
	public static final int HIT_SWEEP = 0x4;
	public static final int HIT_FIRE = 0x8;
	// enum HitWeapon
	public static final int WEAPON_UNARMED = 0;
	public static final int WEAPON_BLADE = 1;
	public static final int WEAPON_AXE = 2;
	public static final int WEAPON_BLUNT = 3;
	public static final int WEAPON_PIERCE = 4;
	public static final int WEAPON_ARROW = 5;
	public static final long ME_TYPE = 0x00L;
	public static final long ME_ENT_ID = 0x04L;
	public static final long ME_STEAM_ID = 0x08L;
	public static final long ME_A = 0x10L;
	public static final long ME_B = 0x14L;
	public static final long ME_C = 0x18L;
	public static final long ME_D = 0x1CL;
	public static final long ME_FLAGS = 0x20L;
	public static final long ME_WEAPON = 0x24L;
	public static final long ME_REQUEST_ID = 0x28L;
	public static final long ME_RESULT = 0x2CL;
	public static final long MC_EVENT_BYTES = 48L;
	public static final long EVENT_RING_BYTES = 0xC080L;

	// block ring @kSvOffBlockRing (MC server -> host)
	public static final long BR_HEAD = 0x00L;
	public static final long BR_TAIL = 0x40L;
	public static final long BR_DATA = 0x80L;
	public static final long BLOCK_BITS_BYTES = 512L;
	public static final long BLOCK_SHAPE_BYTES = 4096L;
	public static final int SHAPE_BOTTOM_SLAB = 0x33;
	public static final int SHAPE_TOP_SLAB = 0xCC;
	// enum BlockMsgType
	public static final int BLK_PAD = 0;
	public static final int BLK_CLEAR_ALL = 1;
	public static final int BLK_SOLIDS = 2;
	public static final int BLK_DUG = 3;
	public static final int BLK_SHAPES = 4;
	public static final int BLK_MICRO = 5;
	public static final long MICRO_CELL_HEADER_BYTES = 3L;
	public static final long MICRO_BOX_BYTES = 6L;
	public static final int MICRO_MAX_PARTS = 64;
	public static final int MICRO_EIGHTHS = 8;
	public static final long MICRO_MAX_BYTES = 0x20000L;
}
